{{- if .Values.route.enabled -}}
{{- $fullName := include "bitwarden-openshift.fullname" . -}}
{{- $ingressPath := .Values.route.path -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
    app.kubernetes.io/name: {{ include "bitwarden-openshift.name" . }}
    helm.sh/chart: {{ include "bitwarden-openshift.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.route.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name: {{ $fullName }}
{{- if .Values.route.tls }}
  tls:
    insecureEdgeTerminationPolicy: {{ .Values.route.insecureEdgeTerminationPolicy }}
    termination: {{ .Values.route.termination }}
{{- end }}
{{- end }}

